# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='foo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='simVect',
            field=models.CharField(default='', max_length=200),
        ),
    ]
