# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20170714_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='check',
            field=models.BooleanField(default=0),
        ),
    ]
