# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_userprofile_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='check',
        ),
    ]
