# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-11 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_userprofile_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='check',
            field=models.BooleanField(default=0),
        ),
    ]
