# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 14:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField(blank=True, max_length=150)),
            ],
            options={
                'permissions': (('can_comment', 'can comment the review'),),
            },
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=50)),
                ('testo', models.TextField()),
                ('voto', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
                ('rank', models.IntegerField(default=50)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('nome', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('recensione', models.ManyToManyField(to='recensioni.Recensione')),
            ],
        ),
        migrations.AddField(
            model_name='commento',
            name='recensione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recensioni.Recensione'),
        ),
    ]
