# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0002_auto_20170701_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='genere',
            field=models.CharField(default='sconosciuto', max_length=50),
        ),
    ]
