# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-03 16:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recensioni', '0003_recensione_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='commento',
            name='autore',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
