# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0004_commento_autore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commento',
            options={},
        ),
    ]
