# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-05 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0005_auto_20170704_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='commento',
            name='voto',
            field=models.NullBooleanField(default=0),
        ),
    ]
