# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0007_auto_20170805_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commento',
            name='autore',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='autore',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
