# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0009_auto_20171110_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commento',
            name='recensione',
            field=models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='recensioni.Recensione'),
        ),
    ]
