# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0010_auto_20171110_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='nclicks',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='commento',
            name='recensione',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recensioni.Recensione'),
        ),
    ]
