# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-10 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recensioni', '0012_auto_20171110_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='nclicks',
            field=models.IntegerField(default=0),
        ),
    ]
